# ==============================================================================
# Supplementary Figure Y — Within-host variant calling diagnostics
#
# Three-panel diagnostic figure characterising the within-host variant data:
#
# Panel a: Distribution of iSNV counts per sample
#          (3-50% minor allele frequency window)
# Panel b: iSNV count vs Ct value (scatter + LOESS fit)
# Panel c: Site frequency spectrum across all variant calls
#
# Inputs (small files from cluster — copy to your desktop):
#   - per_sample_iSNV_counts.tsv       (generated by helper script)
#   - all_variant_frequencies.tsv      (generated by helper script)
#   - VW_lineage.csv or similar with Ct column (or a separate Ct file)
# ==============================================================================

# ----------- USER PATHS ----------------------------------------------------
input_dir  <- "~/UCL Dropbox/Laura Buggiotti/Mac/Desktop/VirusWatch/bottleneck_figures"
output_dir <- "~/UCL Dropbox/Laura Buggiotti/Mac/Desktop/VirusWatch/bottleneck_figures/output"

isnv_counts_path <- file.path(input_dir, "per_sample_iSNV_counts.tsv")
all_freqs_path   <- file.path(input_dir, "all_variant_frequencies.tsv")
ct_data_path     <- file.path(input_dir, "sample_ct_values.csv")  # optional
# ---------------------------------------------------------------------------

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Install missing packages
required <- c("dplyr","tidyr","ggplot2","cowplot","scales","readr")
missing <- required[!required %in% installed.packages()[,"Package"]]
if (length(missing) > 0) install.packages(missing, repos = "https://cloud.r-project.org")

suppressPackageStartupMessages({
  library(dplyr); library(tidyr); library(ggplot2)
  library(cowplot); library(scales); library(readr)
})

# Defensive masking to avoid ggplot2::margin conflicts
margin <- ggplot2::margin

# ============================================================================
# Panel A: distribution of iSNV counts per sample
# ============================================================================

isnv_counts <- read_tsv(isnv_counts_path, show_col_types = FALSE)
# Expected columns: sample, n_isnv

cat("Samples in dataset:", nrow(isnv_counts), "\n")
cat("Median iSNV per sample:", median(isnv_counts$n_isnv), "\n")
cat("IQR:", paste(quantile(isnv_counts$n_isnv, c(0.25, 0.75)), collapse = " - "), "\n")
cat("Range:", min(isnv_counts$n_isnv), "-", max(isnv_counts$n_isnv), "\n")

panel_a <- ggplot(isnv_counts, aes(x = n_isnv)) +
  geom_histogram(binwidth = 1, fill = "steelblue", colour = "white", alpha = 0.85) +
  geom_vline(xintercept = median(isnv_counts$n_isnv),
             linetype = "dashed", colour = "darkred", linewidth = 0.6) +
  annotate("text",
           x = median(isnv_counts$n_isnv) + 0.5,
           y = Inf, vjust = 2,
           label = sprintf("median = %d", median(isnv_counts$n_isnv)),
           colour = "darkred", size = 3.5, hjust = 0) +
  labs(x = "Number of within-host iSNVs per sample (3-50% MAF)",
       y = "Number of samples") +
  theme_bw() +
  theme(
    axis.title = element_text(size = 11, face = "bold"),
    axis.text = element_text(size = 10),
    panel.grid.minor = element_blank(),
    plot.margin = margin(t = 10, r = 15, b = 10, l = 15)
  )

# ============================================================================
# Panel B: iSNV count vs Ct
# ============================================================================

if (file.exists(ct_data_path)) {
  # Try comma first, then tab — your file uses tabs despite .csv extension
  ct_data <- tryCatch(
    {
      d <- read_csv(ct_data_path, show_col_types = FALSE)
      # If we got a single column with embedded tabs, it's actually TSV
      if (ncol(d) == 1 && grepl("\t", names(d)[1])) {
        d <- read_tsv(ct_data_path, show_col_types = FALSE)
      }
      d
    },
    error = function(e) read_tsv(ct_data_path, show_col_types = FALSE)
  )
  
  # Standardise column names — handle "Sample", "CT", "VL (cp/ml)" etc.
  names(ct_data) <- tolower(names(ct_data))
  if ("sample_id" %in% names(ct_data)) {
    ct_data <- ct_data %>% rename(sample = sample_id)
  }
  # Locate the viral load column (header may include units / spaces)
  vl_col <- grep("^vl|viral.?load", names(ct_data), value = TRUE)[1]
  if (!is.na(vl_col)) {
    # Rename using names<- to avoid all_of() issues
    names(ct_data)[names(ct_data) == vl_col] <- "vl"
    ct_data$vl <- as.numeric(ct_data$vl)
  }
  ct_data$ct <- as.numeric(ct_data$ct)
  
  merged <- isnv_counts %>%
    inner_join(ct_data, by = "sample") %>%
    filter(!is.na(ct))
  
  cat("\nSamples with Ct data:", nrow(merged), "\n")
  
  # Spearman correlation
  cor_test <- cor.test(merged$ct, merged$n_isnv, method = "spearman")
  cat(sprintf("Spearman rho (Ct vs iSNV) = %.3f, p = %.3g\n",
              cor_test$estimate, cor_test$p.value))
  
  panel_b <- ggplot(merged, aes(x = ct, y = n_isnv)) +
    geom_point(alpha = 0.5, colour = "steelblue", size = 1.5) +
    geom_smooth(method = "loess", se = TRUE, colour = "darkred",
                fill = "darkred", alpha = 0.15, linewidth = 0.7) +
    annotate("text", x = -Inf, y = Inf, hjust = -0.1, vjust = 2,
             label = sprintf("Spearman \u03C1 = %.2f\np = %s",
                             cor_test$estimate,
                             format.pval(cor_test$p.value, digits = 2)),
             size = 3.2) +
    labs(x = "Ct value",
         y = "iSNVs per sample (3-50% MAF)") +
    theme_bw() +
    theme(
      axis.title = element_text(size = 11, face = "bold"),
      axis.text = element_text(size = 10),
      panel.grid.minor = element_blank(),
      plot.margin = margin(t = 10, r = 15, b = 10, l = 15)
    )
  
  # If viral load is available, also build a viral-load version
  if ("vl" %in% names(merged) && sum(!is.na(merged$vl)) > 5) {
    vl_data <- merged %>% filter(!is.na(vl), vl > 0)
    cor_vl <- cor.test(log10(vl_data$vl), vl_data$n_isnv, method = "spearman")
    cat(sprintf("Spearman rho (log10(VL) vs iSNV) = %.3f, p = %.3g\n",
                cor_vl$estimate, cor_vl$p.value))
    
    panel_b_vl <- ggplot(vl_data, aes(x = vl, y = n_isnv)) +
      geom_point(alpha = 0.5, colour = "steelblue", size = 1.5) +
      geom_smooth(method = "loess", se = TRUE, colour = "darkred",
                  fill = "darkred", alpha = 0.15, linewidth = 0.7) +
      scale_x_log10(labels = scales::trans_format("log10",
                                                  scales::math_format(10^.x))) +
      annotate("text", x = -Inf, y = Inf, hjust = -0.1, vjust = 2,
               label = sprintf("Spearman \u03C1 = %.2f\np = %s",
                               cor_vl$estimate,
                               format.pval(cor_vl$p.value, digits = 2)),
               size = 3.2) +
      labs(x = "Viral load (copies/mL, log scale)",
           y = "iSNVs per sample (3-50% MAF)") +
      theme_bw() +
      theme(
        axis.title = element_text(size = 11, face = "bold"),
        axis.text = element_text(size = 10),
        panel.grid.minor = element_blank(),
        plot.margin = margin(t = 10, r = 15, b = 10, l = 15)
      )
  } else {
    panel_b_vl <- NULL
  }
} else {
  cat("\nNo Ct data file found at", ct_data_path, "\n")
  cat("Panel B will show a placeholder.\n")
  panel_b <- ggplot() +
    annotate("text", x = 0, y = 0,
             label = "Ct data not provided.\nProvide sample_ct_values.csv with\ncolumns: sample, Ct",
             size = 4) +
    theme_void()
  panel_b_vl <- NULL
}


# ============================================================================
# Panel C: site frequency spectrum
# ============================================================================

all_freqs <- read_tsv(all_freqs_path, show_col_types = FALSE)
# Expected columns: sample, position, ref, alt, alt_freq, minor_freq

cat("\nTotal variant observations:", nrow(all_freqs), "\n")

panel_c <- ggplot(all_freqs, aes(x = minor_freq)) +
  geom_histogram(binwidth = 0.01, fill = "darkorange", colour = "white",
                 alpha = 0.85) +
  scale_x_continuous(
    name = "Minor allele frequency",
    breaks = c(0.03, 0.10, 0.20, 0.30, 0.40, 0.50),
    limits = c(0.025, 0.505)
  ) +
  labs(y = "Number of variant calls") +
  theme_bw() +
  theme(
    axis.title = element_text(size = 11, face = "bold"),
    axis.text = element_text(size = 10),
    panel.grid.minor = element_blank(),
    plot.margin = margin(t = 10, r = 15, b = 10, l = 15)
  )

# ============================================================================
# Assemble
# ============================================================================

if (!is.null(panel_b_vl)) {
  # 4-panel layout: A on top, B+B' middle, C bottom
  middle_row <- plot_grid(panel_b, panel_b_vl,
                          ncol = 2,
                          labels = c("b", "c"),
                          label_size = 18)
  final_fig <- plot_grid(
    panel_a, middle_row, panel_c,
    ncol = 1,
    labels = c("a", "", "d"),
    label_size = 18,
    rel_heights = c(1, 1, 1)
  )
  fig_height <- 12
} else {
  final_fig <- plot_grid(
    panel_a, panel_b, panel_c,
    ncol = 1,
    labels = c("a", "b", "c"),
    label_size = 18,
    rel_heights = c(1, 1, 1)
  )
  fig_height <- 11
}

ggsave(file.path(output_dir, "SuppFigY_isnv_diagnostics.pdf"),
       plot = final_fig, width = 9, height = fig_height)
ggsave(file.path(output_dir, "SuppFigY_isnv_diagnostics.png"),
       plot = final_fig, width = 9, height = fig_height, dpi = 300)

cat("\nFigure saved to:", file.path(output_dir, "SuppFigY_isnv_diagnostics.pdf"), "\n")